In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Diện tích dân số.xlsx', sheet_name='Sheet1')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 910 entries, 0 to 909
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Địa phương                       910 non-null    object
 1   Năm                              910 non-null    int64
 2   Diện tích(Km2)                   910 non-null    object
 3   Dân số trung bình (Nghìn người)  910 non-null    object
 4   Mật độ dân số (Người/km2)        910 non-null    object
 5   Diện tích(Km2)(*)                910 non-null    object
 6   Diện tích (Km2)(*)               910 non-null    object
dtypes: int64(1), object(6)
memory usage: 49.9+ KB

,Địa phương,Năm,Diện tích(Km2),Dân số trung bình (Nghìn người),Mật độ dân số (Người/km2),Diện tích(Km2)(*),Diện tích (Km2)(*)
0,Đồng Tháp,2011,"3377,0","1653,2","489,6",..,..
1,Đồng Tháp,2012,"3377,0","1646,2","487,5",..,..
2,Đồng Tháp,2013,"3378,8","1639,2","485,1",..,..
3,Đồng Tháp,2014,"3378,8","1632,4","483,1",..,..
4,Đồng Tháp,2015,"3378,8","1625,6","481,1",..,..
...,...,...,...,...,...,...,...
905,An Giang,2019,..,"1907,4","539,0","3536,7",..
906,An Giang,2020,..,"1904,5","538,0",..,"3536,8"
907,An Giang,2021,..,"1909,5","540,0","3536,8",..
908,An Giang,2022,..,"1905,5","539,0","3536,8",..
909,An Giang,2023,..,"1906,3","539,0","3536,8",..

In [3]:
df.drop(columns=['Diện tích(Km2)(*)', 'Diện tích (Km2)(*)'], inplace=True)
df

,Địa phương,Năm,Diện tích(Km2),Dân số trung bình (Nghìn người),Mật độ dân số (Người/km2)
0,Đồng Tháp,2011,"3377,0","1653,2","489,6"
1,Đồng Tháp,2012,"3377,0","1646,2","487,5"
2,Đồng Tháp,2013,"3378,8","1639,2","485,1"
3,Đồng Tháp,2014,"3378,8","1632,4","483,1"
4,Đồng Tháp,2015,"3378,8","1625,6","481,1"
...,...,...,...,...,...
905,An Giang,2019,..,"1907,4","539,0"
906,An Giang,2020,..,"1904,5","538,0"
907,An Giang,2021,..,"1909,5","540,0"
908,An Giang,2022,..,"1905,5","539,0"
909,An Giang,2023,..,"1906,3","539,0"

In [4]:
df = df[(df['Địa phương'].str.count(' ') <= 2) & (~df['Địa phương'].isin(['CẢ NƯỚC', 'Đông Nam Bộ']))]
df

,Địa phương,Năm,Diện tích(Km2),Dân số trung bình (Nghìn người),Mật độ dân số (Người/km2)
0,Đồng Tháp,2011,"3377,0","1653,2","489,6"
1,Đồng Tháp,2012,"3377,0","1646,2","487,5"
2,Đồng Tháp,2013,"3378,8","1639,2","485,1"
3,Đồng Tháp,2014,"3378,8","1632,4","483,1"
4,Đồng Tháp,2015,"3378,8","1625,6","481,1"
...,...,...,...,...,...
905,An Giang,2019,..,"1907,4","539,0"
906,An Giang,2020,..,"1904,5","538,0"
907,An Giang,2021,..,"1909,5","540,0"
908,An Giang,2022,..,"1905,5","539,0"
909,An Giang,2023,..,"1906,3","539,0"

In [5]:
# Bước 1: Chuyển '..' thành NaN
df['Diện tích(Km2)'] = df['Diện tích(Km2)'].replace('..', pd.NA)

# Bước 1: Điền giá trị NaN bằng giá trị trước đó (ffill)    
df['Diện tích(Km2)'] = df['Diện tích(Km2)'].fillna(method='ffill')

# Bước 2: Đổi dấu phẩy sang chấm để xử lý số thập phân
df['Diện tích(Km2)'] = df['Diện tích(Km2)'].str.replace(',', '.', regex=False).astype(float)

df

C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\2383859747.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Diện tích(Km2)'] = df['Diện tích(Km2)'].replace('..', pd.NA)
C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\2383859747.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Diện tích(Km2)'] = df['Diện tích(Km2)'].fillna(method='ffill')
C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\2383859747.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Diện tích(Km2)'] = df['Diện tích(Km2)'].fillna(method='ffill')
C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\2383859747.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Diện tích(Km2)'] = df['Diện tích(Km2)'].str.replace(',', '.', regex=False).astype(float)

,Địa phương,Năm,Diện tích(Km2),Dân số trung bình (Nghìn người),Mật độ dân số (Người/km2)
0,Đồng Tháp,2011,3377.0,"1653,2","489,6"
1,Đồng Tháp,2012,3377.0,"1646,2","487,5"
2,Đồng Tháp,2013,3378.8,"1639,2","485,1"
3,Đồng Tháp,2014,3378.8,"1632,4","483,1"
4,Đồng Tháp,2015,3378.8,"1625,6","481,1"
...,...,...,...,...,...
905,An Giang,2019,3536.7,"1907,4","539,0"
906,An Giang,2020,3536.7,"1904,5","538,0"
907,An Giang,2021,3536.7,"1909,5","540,0"
908,An Giang,2022,3536.7,"1905,5","539,0"
909,An Giang,2023,3536.7,"1906,3","539,0"

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 909
Data columns (total 5 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Địa phương                       819 non-null    object
 1   Năm                              819 non-null    int64
 2   Diện tích(Km2)                   819 non-null    float64
 3   Dân số trung bình (Nghìn người)  819 non-null    object
 4   Mật độ dân số (Người/km2)        819 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 38.4+ KB

In [7]:
df['Mật độ dân số (Người/km2)'] = df['Mật độ dân số (Người/km2)'].str.replace(',', '.', regex=False).astype(float)
df['Dân số trung bình (Nghìn người)'] = df['Dân số trung bình (Nghìn người)'].str.replace(',', '.', regex=False).astype(float)
df

C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\2437848768.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mật độ dân số (Người/km2)'] = df['Mật độ dân số (Người/km2)'].str.replace(',', '.', regex=False).astype(float)
C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\2437848768.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dân số trung bình (Nghìn người)'] = df['Dân số trung bình (Nghìn người)'].str.replace(',', '.', regex=False).astype(float)

,Địa phương,Năm,Diện tích(Km2),Dân số trung bình (Nghìn người),Mật độ dân số (Người/km2)
0,Đồng Tháp,2011,3377.0,1653.2,489.6
1,Đồng Tháp,2012,3377.0,1646.2,487.5
2,Đồng Tháp,2013,3378.8,1639.2,485.1
3,Đồng Tháp,2014,3378.8,1632.4,483.1
4,Đồng Tháp,2015,3378.8,1625.6,481.1
...,...,...,...,...,...
905,An Giang,2019,3536.7,1907.4,539.0
906,An Giang,2020,3536.7,1904.5,538.0
907,An Giang,2021,3536.7,1909.5,540.0
908,An Giang,2022,3536.7,1905.5,539.0
909,An Giang,2023,3536.7,1906.3,539.0

In [ ]:
df['Dân số trung bình (Nghìn người)'] = df['Dân số trung bình (Nghìn người)']*1000
df.rename(columns={'Dân số trung bình (Nghìn người)': 'Dân số trung bình'}, inplace=True)
df

C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\3995629329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dân số trung bình (Nghìn người)'] = df['Dân số trung bình (Nghìn người)']*1000
C:\Users\Giang\AppData\Local\Temp\ipykernel_17428\3995629329.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Dân số trung bình (Nghìn người)': 'Dân số trung bình (Triệu Người)'}, inplace=True)

In [9]:
df.to_csv('dientich_danso_clean.csv', index=False, encoding='utf-8-sig')